#Admin settings
ongr_settings_personal_settings:
    path: /settings
    defaults:
        _controller: ONGRSettingsBundle:PersonalSettings:settings

ongr_settings_personal_settings_change:
    path: /setting/change/{encodedName}
    defaults:
        _controller: ONGRSettingsBundle:PersonalSettings:changeSetting
        methods: [GET]