#Common settings
ongr_settings_homepage:
    pattern:  /
    methods: [GET]
    defaults:
        _controller: ONGRSettingsBundle:SettingsList:list
        profile: 'default'

ongr_settings_settings_list:
    pattern:  /list/{profile}
    methods: [GET]
    defaults:
        _controller: ONGRSettingsBundle:SettingsList:list
        profile: 'default'

ongr_settings_setting_set:
    pattern:  /setting/set/{name}/{profile}
    methods: [POST]
    defaults:
        _controller: ONGRSettingsBundle:SettingsManager:setSetting
        profile: 'default'

ongr_settings_setting_edit:
    pattern:  /setting/{name}/edit/{profile}
    methods: [GET, POST]
    defaults:
        _controller: ONGRSettingsBundle:SettingsManager:edit
        profile: 'default'
    options:
        expose: true

ongr_settings_setting_ng_edit:
    pattern:  /setting/ng/{name}/edit/{profile}
    methods: [POST]
    defaults:
        _controller: ONGRSettingsBundle:SettingsManager:ngEdit
        profile: 'default'
    options:
        expose: true

ongr_settings_setting_remove:
    pattern:  /setting/{name}/remove/{profile}
    methods: [DELETE]
    defaults:
        _controller: ONGRSettingsBundle:SettingsManager:remove
        profile: 'default'
    options:
        expose: true

ongr_settings_setting_copy:
    pattern:  /setting/{name}/copy/{from}/{to}
    methods: [GET]
    defaults:
        _controller: ONGRSettingsBundle:SettingsManager:copy
        from: 'default'
    options:
        expose: true